//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yandex.Metro.Resourses {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yandex.Metro.Resourses.Localization", typeof(Localization).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на METRO.
        /// </summary>
        internal static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application needs to relaunched..
        /// </summary>
        internal static string ApplicationFailed_MessageLine1 {
            get {
                return ResourceManager.GetString("ApplicationFailed_MessageLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please tap &quot;OK&quot; to send Yandex a bug report..
        /// </summary>
        internal static string ApplicationFailed_MessageLine2 {
            get {
                return ResourceManager.GetString("ApplicationFailed_MessageLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Phone Metro mobile app.
        /// </summary>
        internal static string ApplicationFailed_Subject {
            get {
                return ResourceManager.GetString("ApplicationFailed_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string ApplicationFailed_Title {
            get {
                return ResourceManager.GetString("ApplicationFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Build {0}.{1}.
        /// </summary>
        internal static string BuildFormat {
            get {
                return ResourceManager.GetString("BuildFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kharkiv.
        /// </summary>
        internal static string City_Kharkiv {
            get {
                return ResourceManager.GetString("City_Kharkiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kiev.
        /// </summary>
        internal static string City_Kiev {
            get {
                return ResourceManager.GetString("City_Kiev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minsk.
        /// </summary>
        internal static string City_Minsk {
            get {
                return ResourceManager.GetString("City_Minsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moscow.
        /// </summary>
        internal static string City_Moscow {
            get {
                return ResourceManager.GetString("City_Moscow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saint Petersburg.
        /// </summary>
        internal static string City_SaintPetersburg {
            get {
                return ResourceManager.GetString("City_SaintPetersburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на © {0} YANDEX.
        /// </summary>
        internal static string CopyrightFormat {
            get {
                return ResourceManager.GetString("CopyrightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Belarus.
        /// </summary>
        internal static string Country_Belarus {
            get {
                return ResourceManager.GetString("Country_Belarus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russia.
        /// </summary>
        internal static string Country_Russia {
            get {
                return ResourceManager.GetString("Country_Russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ukraine.
        /// </summary>
        internal static string Country_Ukraine {
            get {
                return ResourceManager.GetString("Country_Ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find city automatically?.
        /// </summary>
        internal static string DetectCity_Text {
            get {
                return ResourceManager.GetString("DetectCity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на City detecting.
        /// </summary>
        internal static string DetectCity_Title {
            get {
                return ResourceManager.GetString("DetectCity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App version.
        /// </summary>
        internal static string ErrorReport_AppVersion {
            get {
                return ResourceManager.GetString("ErrorReport_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current page.
        /// </summary>
        internal static string ErrorReport_CurrentPage {
            get {
                return ResourceManager.GetString("ErrorReport_CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please provide a detailed description of the problem:.
        /// </summary>
        internal static string ErrorReport_Line1 {
            get {
                return ResourceManager.GetString("ErrorReport_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information that will help us resolve the issue as soon as possible.
        /// </summary>
        internal static string ErrorReport_Line3 {
            get {
                return ResourceManager.GetString("ErrorReport_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Telephone model.
        /// </summary>
        internal static string ErrorReport_Model {
            get {
                return ResourceManager.GetString("ErrorReport_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not specified.
        /// </summary>
        internal static string ErrorReport_NoPage {
            get {
                return ResourceManager.GetString("ErrorReport_NoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operating system version.
        /// </summary>
        internal static string ErrorReport_OSVersion {
            get {
                return ResourceManager.GetString("ErrorReport_OSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add to favorites.
        /// </summary>
        internal static string Favorite_Title {
            get {
                return ResourceManager.GetString("Favorite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add.
        /// </summary>
        internal static string FavoriteButton_Add {
            get {
                return ResourceManager.GetString("FavoriteButton_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на edit.
        /// </summary>
        internal static string FavoriteButton_Edit {
            get {
                return ResourceManager.GetString("FavoriteButton_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на remove.
        /// </summary>
        internal static string FavoriteButton_Remove {
            get {
                return ResourceManager.GetString("FavoriteButton_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Belorussian.
        /// </summary>
        internal static string Language_Bel {
            get {
                return ResourceManager.GetString("Language_Bel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string Language_En {
            get {
                return ResourceManager.GetString("Language_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        internal static string Language_Rus {
            get {
                return ResourceManager.GetString("Language_Rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ukrainian.
        /// </summary>
        internal static string Language_Ukr {
            get {
                return ResourceManager.GetString("Language_Ukr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на license agreement.
        /// </summary>
        internal static string LicenseAgreement {
            get {
                return ResourceManager.GetString("LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End:.
        /// </summary>
        internal static string Map_End {
            get {
                return ResourceManager.GetString("Map_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From here.
        /// </summary>
        internal static string Map_From {
            get {
                return ResourceManager.GetString("Map_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hour.
        /// </summary>
        internal static string Map_Hour {
            get {
                return ResourceManager.GetString("Map_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на min.
        /// </summary>
        internal static string Map_Minute {
            get {
                return ResourceManager.GetString("Map_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invert path.
        /// </summary>
        internal static string Map_RevertRoute {
            get {
                return ResourceManager.GetString("Map_RevertRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start:.
        /// </summary>
        internal static string Map_Start {
            get {
                return ResourceManager.GetString("Map_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Here.
        /// </summary>
        internal static string Map_To {
            get {
                return ResourceManager.GetString("Map_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на clear route.
        /// </summary>
        internal static string Menu_ClearRoute {
            get {
                return ResourceManager.GetString("Menu_ClearRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на favorites.
        /// </summary>
        internal static string Menu_Favorites {
            get {
                return ResourceManager.GetString("Menu_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на plain map.
        /// </summary>
        internal static string Menu_PlainMap {
            get {
                return ResourceManager.GetString("Menu_PlainMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subway is closed from {0} till {1}.
        /// </summary>
        internal static string Metro_WorkTimeMessage {
            get {
                return ResourceManager.GetString("Metro_WorkTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на подорожник.
        /// </summary>
        internal static string Podorosnik {
            get {
                return ResourceManager.GetString("Podorosnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For information about the location, use the &quot;Locate&quot;, which is used to find the nearest metro station..
        /// </summary>
        internal static string Policy_ContentLine1 {
            get {
                return ResourceManager.GetString("Policy_ContentLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By clicking &quot;Allow&quot;, you agree to the transfer of data to the conditions specified in the license agreement..
        /// </summary>
        internal static string Policy_ContentLine2 {
            get {
                return ResourceManager.GetString("Policy_ContentLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow the program &quot;Yandex.Metro&quot; to use the information about the location?.
        /// </summary>
        internal static string Policy_Title {
            get {
                return ResourceManager.GetString("Policy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow.
        /// </summary>
        internal static string PolicyButton_Allow {
            get {
                return ResourceManager.GetString("PolicyButton_Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string PolicyButton_Cancel {
            get {
                return ResourceManager.GetString("PolicyButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License agreement.
        /// </summary>
        internal static string PolicyButton_LicenseAgreement {
            get {
                return ResourceManager.GetString("PolicyButton_LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading map.
        /// </summary>
        internal static string Progress_LoadingMap {
            get {
                return ResourceManager.GetString("Progress_LoadingMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading map....
        /// </summary>
        internal static string Progress_Map {
            get {
                return ResourceManager.GetString("Progress_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading route....
        /// </summary>
        internal static string Progress_Route {
            get {
                return ResourceManager.GetString("Progress_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quick search.
        /// </summary>
        internal static string Progress_Suggest {
            get {
                return ResourceManager.GetString("Progress_Suggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updating schemes....
        /// </summary>
        internal static string Progress_UpdateScheme {
            get {
                return ResourceManager.GetString("Progress_UpdateScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no search results.
        /// </summary>
        internal static string Search_Empty {
            get {
                return ResourceManager.GetString("Search_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на about.
        /// </summary>
        internal static string Settings_AboutTitle {
            get {
                return ResourceManager.GetString("Settings_AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на allow rotation.
        /// </summary>
        internal static string Settings_AllowRotation {
            get {
                return ResourceManager.GetString("Settings_AllowRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на City.
        /// </summary>
        internal static string Settings_City {
            get {
                return ResourceManager.GetString("Settings_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autoselect Start-End.
        /// </summary>
        internal static string Settings_GpsContent {
            get {
                return ResourceManager.GetString("Settings_GpsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consider my location.
        /// </summary>
        internal static string Settings_GpsTitle {
            get {
                return ResourceManager.GetString("Settings_GpsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на settings.
        /// </summary>
        internal static string Settings_SettingsTitle {
            get {
                return ResourceManager.GetString("Settings_SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updated  {0}.
        /// </summary>
        internal static string Settings_UpdateText {
            get {
                return ResourceManager.GetString("Settings_UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find new stations.
        /// </summary>
        internal static string Settings_UpdateTitle {
            get {
                return ResourceManager.GetString("Settings_UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear current path?.
        /// </summary>
        internal static string Shake_Text {
            get {
                return ResourceManager.GetString("Shake_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        internal static string ShakeButton_No {
            get {
                return ResourceManager.GetString("ShakeButton_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        internal static string ShakeButton_Yes {
            get {
                return ResourceManager.GetString("ShakeButton_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a..z.
        /// </summary>
        internal static string Station_AZ {
            get {
                return ResourceManager.GetString("Station_AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на destination.
        /// </summary>
        internal static string Station_Destination {
            get {
                return ResourceManager.GetString("Station_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dispatch.
        /// </summary>
        internal static string Station_Dispatch {
            get {
                return ResourceManager.GetString("Station_Dispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lines.
        /// </summary>
        internal static string Station_Lines {
            get {
                return ResourceManager.GetString("Station_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Station {0}.
        /// </summary>
        internal static string Station_Title {
            get {
                return ResourceManager.GetString("Station_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scheme update finished!.
        /// </summary>
        internal static string UpdateScheme_Complete {
            get {
                return ResourceManager.GetString("UpdateScheme_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updating schemes.
        /// </summary>
        internal static string UpdateScheme_Header {
            get {
                return ResourceManager.GetString("UpdateScheme_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nothing to update.
        /// </summary>
        internal static string UpdateScheme_UpToDate {
            get {
                return ResourceManager.GetString("UpdateScheme_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your uuid {0}.
        /// </summary>
        internal static string UUID {
            get {
                return ResourceManager.GetString("UUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version {0}.{1:D2}, {2:D}.
        /// </summary>
        internal static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на applications.
        /// </summary>
        internal static string YandexApps_Title {
            get {
                return ResourceManager.GetString("YandexApps_Title", resourceCulture);
            }
        }
    }
}
